name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.SECRET_DOCKER }}
        build-context: ./15.0
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.SECRET_DOCKER }}
        context: ./15.0
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/odoo11:odoo150

